import type { CuratedCollection, Game } from "./types";

export const CATALOG: Array<Omit<Game, "source">> = [
  { id: "zelda-ocarina", title: "The Legend of Zelda: Ocarina of Time", platform: "n64", platformName: "Nintendo 64", year: 1998, genre: "Adventure", developer: "Nintendo EAD", description: "A forest boy. A borrowed horse. A world worth saving. Travel between two eras of Hyrule in the adventure that redefined what a game could be—and still feels like coming home.", cover: "/images/covers/zelda-ocarina.png", color: "#e8e6d9", accent: "#6a7354", rank: 0 },
  { id: "pokemon-emerald", title: "Pokémon Emerald", platform: "gba", platformName: "Game Boy Advance", year: 2004, genre: "RPG", developer: "Game Freak", description: "Take the long way through Hoenn. Catch a new companion, brave the Battle Frontier, and get wonderfully lost in one of the most beloved pocket-sized worlds ever made.", cover: "/images/covers/pokemon-emerald.png", color: "#e2e8db", accent: "#53715b", rank: 1 },
  { id: "mario-64", title: "Super Mario 64", platform: "n64", platformName: "Nintendo 64", year: 1996, genre: "Platformer", developer: "Nintendo EAD", description: "The castle doors are open. Leap into paintings, find a hundred little secrets, and rediscover the pure joy of movement in Mario’s unforgettable first 3D adventure.", cover: "/images/covers/mario-64.png", color: "#e1e8ee", accent: "#637b95", rank: 2 },
  { id: "chrono-trigger", title: "Chrono Trigger", platform: "snes", platformName: "Super Nintendo", year: 1995, genre: "RPG", developer: "Square", description: "An accidental trip through time becomes an adventure across the ages. A timeless cast, an extraordinary soundtrack, and a story you will want to experience more than once.", cover: "/images/covers/chrono-trigger.png", color: "#eee5dc", accent: "#9b785f", rank: 3 },
  { id: "earthbound", title: "EarthBound", platform: "snes", platformName: "Super Nintendo", year: 1994, genre: "RPG", developer: "HAL Laboratory & Ape", description: "Four kids and a very strange world. Leave home with a baseball bat and a big heart in this offbeat, funny, quietly moving adventure through everyday magic.", cover: "/images/covers/earthbound.png", color: "#e5e3ec", accent: "#79708f", rank: 4 },
  { id: "super-metroid", title: "Super Metroid", platform: "snes", platformName: "Super Nintendo", year: 1994, genre: "Adventure", developer: "Nintendo R&D1", description: "Alone on the planet Zebes, every corridor tells a story. Explore a beautifully interconnected world, discover new abilities, and let the atmosphere pull you deeper.", cover: "/images/covers/super-metroid.png", color: "#e4e7df", accent: "#68775c", rank: 5 },
  { id: "ff-vii", title: "Final Fantasy VII", platform: "ps1", platformName: "PlayStation", year: 1997, genre: "RPG", developer: "Square", description: "From the neon streets of Midgar to the edge of the world. Join Cloud and a band of unlikely friends in an ambitious, deeply human story about memory, identity, and the planet.", cover: "/images/covers/ff-vii.png", color: "#e4e9e7", accent: "#618077", rank: 6 },
  { id: "castlevania", title: "Castlevania: Symphony of the Night", platform: "ps1", platformName: "PlayStation", year: 1997, genre: "Adventure", developer: "Konami", description: "Step into a castle that refuses to reveal all its secrets. Elegant exploration, gothic pixel art, and an incredible soundtrack make Alucard’s journey a classic worth revisiting.", cover: "/images/covers/castlevania.png", color: "#e9e1e5", accent: "#8b667b", rank: 7 },
  { id: "zelda-minish", title: "The Legend of Zelda: The Minish Cap", platform: "gba", platformName: "Game Boy Advance", year: 2004, genre: "Adventure", developer: "Flagship & Capcom", description: "Sometimes a smaller world opens up a bigger adventure. Shrink down, make unexpected friends, and discover a charming, beautifully detailed corner of Hyrule.", cover: "/images/covers/zelda-minish.png", color: "#e7ead9", accent: "#7b8154", rank: 8 },
  { id: "golden-sun", title: "Golden Sun", platform: "gba", platformName: "Game Boy Advance", year: 2001, genre: "RPG", developer: "Camelot Software Planning", description: "Gather the Djinn and set out across Weyard. Clever elemental puzzles, grand battles, and a sense of wonder make this a little cartridge with a very big heart.", cover: "/images/covers/golden-sun.png", color: "#eee7d7", accent: "#a0884d", rank: 9 },
  { id: "tetris", title: "Tetris", platform: "gb", platformName: "Game Boy", year: 1989, genre: "Puzzle", developer: "Nintendo R&D1", description: "Seven shapes. Endless possibility. The definitive pick-up-and-play puzzle that turned a humble handheld into a worldwide companion. Just one more line.", cover: "/images/covers/tetris.png", color: "#e7e9db", accent: "#7a835b", rank: 10 },
  { id: "kirby", title: "Kirby’s Dream Land", platform: "gb", platformName: "Game Boy", year: 1992, genre: "Platformer", developer: "HAL Laboratory", description: "A small pink hero makes his big debut. Float through gentle, whimsical landscapes in an adventure that is as warm and welcoming today as it was in 1992.", cover: "/images/covers/kirby.png", color: "#eee1e3", accent: "#a77581", rank: 11 },
  { id: "sonic-2", title: "Sonic the Hedgehog 2", platform: "genesis", platformName: "Sega Genesis", year: 1992, genre: "Platformer", developer: "Sega Technical Institute", description: "Find your rhythm, pick up speed, and bring a friend. Sonic and Tails race through colorful worlds in a defining 16-bit adventure that never stands still.", cover: "/images/covers/sonic-2.png", color: "#dee6ed", accent: "#637fa0", rank: 12 },
  { id: "streets-rage", title: "Streets of Rage 2", platform: "genesis", platformName: "Sega Genesis", year: 1992, genre: "Action", developer: "Sega & Ancient", description: "Neon streets, unforgettable beats, and the best kind of couch co-op. Take back the city in a perfectly paced arcade adventure with a legendary soundtrack.", cover: "/images/covers/streets-rage.png", color: "#e7dfe9", accent: "#876e94", rank: 13 },
  { id: "metal-gear", title: "Metal Gear Solid", platform: "ps1", platformName: "PlayStation", year: 1998, genre: "Action", developer: "Konami Computer Entertainment Japan", description: "Stay out of sight. Listen closely. Snake’s mission on Shadow Moses blends thoughtful stealth with cinematic storytelling in a game that changed the conversation.", cover: "/images/covers/metal-gear.png", color: "#e3e5e4", accent: "#68716e", rank: 14 },
  { id: "yoshi", title: "Super Mario World 2: Yoshi’s Island", platform: "snes", platformName: "Super Nintendo", year: 1995, genre: "Platformer", developer: "Nintendo EAD", description: "A storybook come to life. Guide Yoshi and Baby Mario through a world of crayon colors, clever secrets, and playful surprises—one wonderfully expressive level at a time.", cover: "/images/covers/yoshi.png", color: "#e2e8d9", accent: "#6e8055", rank: 15 },
];

export const CURATED_COLLECTIONS: CuratedCollection[] = [
  { id: "curated-essentials", name: "The essentials", description: "The games that made us fall in love with games.", color: "#e9e7df", eyebrow: "START HERE", curator: "The roms.tn editors", gameIds: ["zelda-ocarina", "mario-64", "chrono-trigger", "super-metroid", "ff-vii", "tetris"] },
  { id: "curated-pocket", name: "Pocket-sized worlds", description: "Small cartridges. Unreasonably big adventures.", color: "#e3e9de", eyebrow: "TAKE IT WITH YOU", curator: "The roms.tn editors", gameIds: ["pokemon-emerald", "zelda-minish", "golden-sun", "kirby", "tetris"] },
  { id: "curated-weekend", name: "One more level", description: "For slow Sundays and just-one-more evenings.", color: "#e7e6ed", eyebrow: "PRESS START", curator: "The roms.tn editors", gameIds: ["mario-64", "sonic-2", "yoshi", "streets-rage", "kirby"] },
];

export const PLATFORM_LABELS: Record<string, string> = { n64: "N64", gba: "GBA", snes: "SNES", ps1: "PS1", gb: "GB", genesis: "SEGA" };
