"use client";

import Image from "next/image";
import { Bookmark, Check, Plus, ArrowUpRight, Leaf, Layers } from "lucide-react";
import { MetalFx } from "./MetalFx";
import { Modal } from "./Modal";
import type { Game, LibraryCollection } from "@/lib/types";

export function GameDetails({ game, saved, collections, busy, onClose, onSave, onToggleCollection, onCreateCollection }: { game: Game; saved: boolean; collections: LibraryCollection[]; busy: boolean; onClose: () => void; onSave: () => void; onToggleCollection: (collectionId: string) => void; onCreateCollection: () => void }) {
  return <Modal title={game.title} onClose={onClose} className="game-detail-modal"><div className="detail-art" style={{ background: game.color }}><span className="eyebrow">A LITTLE PIECE OF GAMING HISTORY</span><Image src={game.cover} alt={`${game.title} original box art`} width={420} height={300} sizes="380px" /><span className="detail-art-caption">ORIGINAL BOX ART · {game.year}</span></div><div className="detail-content"><div className="detail-kicker"><span>{game.platformName}</span><span>·</span><span>{game.year}</span></div><h2>{game.title}</h2><p className="detail-description">{game.description}</p><dl className="game-facts"><div><dt>Genre</dt><dd>{game.genre}</dd></div><div><dt>Developer</dt><dd>{game.developer}</dd></div><div><dt>First released</dt><dd>{game.year}</dd></div></dl><div className="detail-actions"><MetalFx preset="chromatic" strength={1} theme="light"><button className={`primary-button ${saved ? "saved-primary" : ""}`} onClick={onSave} disabled={busy}>{saved ? <Check size={16} /> : <Bookmark size={16} />}{saved ? "Saved to your library" : "Save to your library"}</button></MetalFx><a className="text-button" href={`https://en.wikipedia.org/wiki/${encodeURIComponent(game.title.replace(/ /g, "_"))}`} target="_blank" rel="noreferrer">The story behind it <ArrowUpRight size={15} /></a></div><div className="add-to-collection"><div className="subsection-label"><Layers size={15} /><span>Keep it in a collection</span></div><div className="membership-list">{collections.map((collection) => <button key={collection.id} className={collection.gameIds.includes(game.id) ? "is-member" : ""} disabled={busy} onClick={() => onToggleCollection(collection.id)}><span className="collection-color-dot" style={{ background: collection.color }} />{collection.name}{collection.gameIds.includes(game.id) ? <Check size={14} /> : <Plus size={14} />}</button>)}<button className="new-membership" onClick={onCreateCollection} disabled={busy}><Plus size={14} /> New collection</button></div></div><div className="preservation-note"><Leaf size={16} /><p>We celebrate and document games, not distribute ROMs. Enjoy original copies and respect the creators who made these worlds.</p></div></div></Modal>;
}
